---
title: "Healthcare Coverage in US"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}

img {
  margin: 40px;
}

</style>

<div class="row" style="padding-top: 100px;">




# Introduction

## Goals of the project

In this project, we present a _state-level overview_ of the expansion of health insurance in the United States and its effects on health outcomes and cost outcomes, from 2008 to 2015 under President Obama's term. One of the hallmarks of Obama's presidency was the passage and implementation of the __Affordable Care Act (ACA)__ to increase health insurance coverage and regulate healthcare provision to protect consumers' rights. In addition, we are also interested in how people perceive the (ACA), as seen from articles related to the ACA from the New York Times and Twitter.

__Research Questions:__

1) _Trends of health insurance expansion in the United States_: How has the percentage of uninsured Americans changed overall, and differentially by states, from 2008 to 2015? How has the composition of healthcare sources changed?

2) _Health outcomes_: How do the states compare in health outcomes, such as mortality rates and access to preventative and remedying treatments?

3) _Financial outcomes_: How do the states compare in financial and cost outcomes, such as the containment of out-of-pocket costs, insurance premium growth and government spending?

4) _Perceptions of the ACA_: We used API to download articles realted to ACA on New York Times from 2011-2017 and transformed them into a corpus to conduct a text analysis. How has the overall trend of public attention changed over the years, as seen by the number of articles relating to the ACA? What topics do people focus on when they discuss the ACA on Twitter?

## Overview of the Affordable Care Act in the United States

The __Patient Protection and Affordable Care Act (ACA)__, also commonly known as Obamacare, was a major and wide-sweeping healthcare reform initiative enacted by Preseident Obama. The ACA was signed into law by Obama on March 23, 2010, and changes were gradually implemented over the next few years, though the majority of the provisions went into effect only on January 1, 2014.   

The major goal of the ACA is to expand health insurance and healthcare access to those who otherwise did not have access, including the 45 million Americans who were uninsured before the ACA took effect. In addition, it also covers wide-ranging regulations for the protection of healthcare consumer rights. Prior to the ACA, many low-income Americans we unable to afford any health insurance, while people with disabilities and pre-existing conditions may have been denied coverage by insurerers.   

__The key provisions of the ACA include__  

_Employer mandate_: Employers with more than 50 employees are required to provide health insurance to full-time workers, or would otherwise face a fine

_Individual mandate_: Individuals must obtain "minimum essential coverage" for healthcare, and those without health insurance must pay a fine in their annual tax returns to the IRS

_State and federal marketplaces_: These health insurance exchanges were set-up to enable people "shopping" for insurance to make easy comparisons among the insurance plans available, thus inreasing competition in the marketplace as well.

_Medicaid expansion_: The ACA expands medicaid to all individuals earning less than 138% of the federal poverty level (FPL), enabled first by federal funding and . After the Supreme Court ruled this requirement as unconstitutional (thus optional) in 2012, 31 states have elected to expand medicaid, while 19 have not.

_Federal subsidies_ to people earning between 138% and 400% of the FPL to afford monthly health insurance premiums.

_Regulations_ preventing insurance companies from discriminating in price and provision based on people's age, gender, or pre-existing conditions

These provisions of the ACA make health insurance accessible and affordable to people previously without coverage. In addition, people who already have health insurance would also benefit from increased choice, a cap on out-of-pocket expenses, as well as more comprehensive coverage, as insurance is now required to cover more basic treatments than before.

However, this increased coverage comes at a cost of increased premium growths for consumers, and increases in federal spending. The expansion of health insurance and healthcare coverage is projected to cost of the U.S. government up to $1.34 trillion over the next decade. It is thus no surprise that the States fall on various sides of the political spectrum when it comes to support for medicaid.

## Perceptions of the ACA in the United States

Except th public data released from governemnt and census source, We are also interested in how people think about Affordable care act(ACA). In this part, we want to have a look of the tweets and newspaper related to ACA.

Research Questions: 1) The overll trend of public attention, which can be shown as the number of articles and tweets related to ACA in different years. 2) What people discuss about when they discuss ACA, which can be shown as the word frequencies and sentiment analysis.

__New York Times__

To realize the perceptions of ACA, we use API to download articles realted to ACA on New york times from 2011-2017 and transform them into corpus to do the text analysis. The reason that we choosed the New York Times as our analysis target is because it is a representative and reputative newspaper in the U.S.

__Twitter__

We got tweets from Twitter API to analyze and visualize the trends of health insurance issues on social media. The data we Selected including ACA, Affordable Care Act, #ACA and obamacare (The popular term for legislation passed in 2010 under the deceptively named Affordable Care Act). The sample sizes is 1000

The Twitter search API allows access to a subset of popular or recent tweets (in the last 4-6 days). That is, it allows querying past tweets (though a significantly small fraction of all tweets). To us, this is a great way to get one's hands wet on collecting and cleaning tweet datasets, however, it doesn't really provide any utility for research as the fraction of tweets received may not really be representative of the entire tweet stream and the sample sizes are limited.

## Future Study

__Public Perceptions of the ACA__

In the current project, due to the time limitation, we only examine the contexts in the New York Times, which represents more liberal voices in the U.S. For more completed study, we will suggest to do text analysis in other newespaper or press media as well, aspecially comparing articles in the different organizations holding different standpoint of views (i.e., the New York Times v.s. the Wall Street Journal).

The limitation of extracting tweets through Twitter API is every Twitter account can only connect to a small sampling of the Streaming API. Also, cleaning data from the messy dataset that we retrieved and determining the boundaries of data collection are quite completed tasks. Although Twitter API does have such limitations, analyzing the trends of Twitter is still helpful to know public perceptions. 
